baseURL = 'http://www.tysonmorris.net'
languageCode = 'en-us'
title = 'Tyson Morris'
theme = 'exampleTheme'

[menu]
  [[menu.main]]
	name = "Home"
	url = "/"
	weight = 1
  [[menu.main]]
	name = "Posts"
	url = "/posts/"
	weight = 2
  [[menu.main]]
	name = "Animations"
	url = "/animations/"
	weight = 3
  [[menu.main]]
	name = "Tags"
	url = "/tags/"
	weight = 4